model:
  channels: 32
  num_blocks: 7
  semantic_classes: 20
  instance_classes: 18
  sem2ins_classes: []
  semantic_only: True
  ignore_label: -100
  grouping_cfg:
    score_thr: 0.2
    radius: 0.04
    mean_active: 300
    class_numpoint_mean: [-1., -1., 3917., 12056., 2303.,
                          8331., 3948., 3166., 5629., 11719.,
                          1003., 3317., 4912., 10221., 3889.,
                          4136., 2120., 945., 3967., 2589.]
    npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: [0, 1]
  instance_voxel_cfg:
    scale: 50
    spatial_shape: 20
  train_cfg:
    max_proposal_num: 200
    pos_iou_thr: 0.5
  test_cfg:
    x4_split: False
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
    eval_tasks: ['semantic']
  fixed_modules: ['input_conv', 'unet']


data:
  train:
    type: 'scannetv2'
    data_root: 'dataset/scannetv2'
    prefix: 'train'
    suffix: '_inst_nostuff_5w.pth'
    # suffix: '_inst_nostuff.pth'
    training: True
    repeat: 4
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 'scannetv2'
    data_root: 'dataset/scannetv2'
    prefix: ['val', 'train']
    suffix: '_inst_nostuff_5w.pth'
    # suffix: '_inst_nostuff.pth'
    training: False
    with_label: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
    # scene_ids: ['scene0269_01', 'scene0000_00', 'scene0572_02']
    # scene_ids: ['scene0269_01'] #圆形家具
    # scene_ids: ['scene0000_00']
    # scene_ids: ['scene0525_01'] # 蓝色
    # scene_ids: ['scene0566_00'] #黑板
    # scene_ids: ['scene0100_02'] #黑板
    scene_ids: ['scene0197_01']

dataloader:
  train:
    batch_size: 4
    num_workers: 4
  test:
    batch_size: 1
    num_workers: 4

optimizer:
  type: 'Adam'
  lr: 0.01

fp16: False
epochs: 20
step_epoch: 10 #8
save_freq: 1
# pretrain: './hais_ckpt_spconv2.pth'
pretrain: 'pth/softgroup_scannet_spconv2.pth'
#pretrain: '/home/wxj/code/P2P/ov-seg/SoftGroup/pre-train/base.pth'
work_dir: ''
